version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_e_learning
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - APPLICATION_URL=${APPLICATION_URL}
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - DATABASE_SSL=${DATABASE_SSL}
      - FOREST_AUTH_SECRET=${FOREST_AUTH_SECRET}
      - FOREST_ENV_SECRET=${FOREST_ENV_SECRET}
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  database_elearning:
    image: postgres:13.5
    container_name: forest_database_elearning
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_DB=elearning
      - POSTGRES_USER=forest
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
