// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Enrollments = sequelize.define('enrollments', {
    status: {
      type: DataTypes.ENUM(
        'enrolled',
        'completed',
        'dropped',
      ),
    },
  }, {
    tableName: 'enrollments',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Enrollments.associate = (models) => {
    Enrollments.belongsTo(models.courses, {
      foreignKey: {
        name: 'courseIdKey',
        field: 'course_id',
      },
      as: 'course',
    });
    Enrollments.belongsTo(models.users, {
      foreignKey: {
        name: 'userIdKey',
        field: 'user_id',
      },
      as: 'user',
    });
  };

  return Enrollments;
};
