// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Lessons = sequelize.define('lessons', {
    title: {
      type: DataTypes.STRING,
    },
    description: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'lessons',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/reference-guide/relationships#adding-relationships.
  Lessons.associate = (models) => {
    Lessons.belongsTo(models.courses, {
      foreignKey: {
        name: 'courseIdKey',
        field: 'course_id',
      },
      as: 'course',
    });
    Lessons.hasMany(models.quizzes, {
      foreignKey: {
        name: 'lessonIdKey',
        field: 'lesson_id',
      },
      as: 'quizzes',
    });
  };

  return Lessons;
};
